"""
scene_evaluator.py — AI-2：3D 场景质量评估员

职责：
  1. evaluate_scene()    — 每次生成后对场景 JSON 进行 0-10 评分（含详细指标）
  2. summarize_and_update() — 每 10 个干净场景后汇总规律，更新 AI-1 的 system_prompt.txt
"""

import json
import re
from pathlib import Path

import requests

from config import (
    DEEPSEEK_API_KEY_2,
    DEEPSEEK_API_URL,
    DEEPSEEK_MODEL,
    DEEPSEEK_EVALUATOR_TEMP,
)

# ---------------------------------------------------------------------------
# AI-2 系统 Prompt：单场景评分
# ---------------------------------------------------------------------------

EVALUATOR_SYSTEM_PROMPT = """You are an expert 3D urban scene quality inspector for a Channel Knowledge Map (CKM) simulation pipeline. Your task is to evaluate the quality of a generated 3D scene described in JSON format.

You will receive:
1. The original text prompt that was used to generate the scene
2. The generated scene JSON (buildings and roads)
3. Overlap information (if any collisions were detected)
4. The attempt number (1 = first try, 2+ = retry after overlap)

Evaluate the scene on EXACTLY these 7 metrics, each scored 0.0–10.0 (one decimal place):

1. building_distribution — Are buildings well-spaced and distributed? Evaluate spacing, density, and coverage across the map. Penalize crowding or extreme sparsity.

2. road_quality — Does the road network look realistic and well-designed? Consider road connectivity, complexity (not just a single cross), variety (straight vs. curved), and whether roads actually pass between buildings.

3. style_consistency — Does the building arrangement match the requested layout style (orthogonal grid / slab row / point scatter / perimeter / radial / cluster / organic)? Penalize if the style keywords in the prompt are ignored.

4. building_diversity — Are buildings varied? Score based on: mix of types (rectangular/l_shaped/t_shaped/u_shaped), spread of heights, variety in width/length dimensions, unique rotation angles.

5. prompt_adherence — Does the scene faithfully follow the text prompt? Check: correct number of buildings, correct types mentioned, correct materials, correct road count, correct TX/RX/RT parameters if mentioned.

6. technical_compliance — Are technical requirements met? Check: all coordinates use 0.01m precision (2 decimal places), rotation_deg present on every building, no duplicate rotation values, no missing required fields (x, y, height, type), road start ≠ end.

7. spatial_efficiency — Is the scene scaled appropriately? Does the number of buildings fit the map size? Are buildings neither too small to matter nor so large they dominate the entire map?

After scoring all 7 metrics, compute overall_score as a holistic assessment (0.0–10.0, NOT a simple average — use your judgment).

Return ONLY valid JSON in this exact format:
{
  "overall_score": <float 0.0-10.0>,
  "metrics": {
    "building_distribution": {"score": <float>, "comment": "<one sentence in Chinese>"},
    "road_quality":          {"score": <float>, "comment": "<one sentence in Chinese>"},
    "style_consistency":     {"score": <float>, "comment": "<one sentence in Chinese>"},
    "building_diversity":    {"score": <float>, "comment": "<one sentence in Chinese>"},
    "prompt_adherence":      {"score": <float>, "comment": "<one sentence in Chinese>"},
    "technical_compliance":  {"score": <float>, "comment": "<one sentence in Chinese>"},
    "spatial_efficiency":    {"score": <float>, "comment": "<one sentence in Chinese>"}
  },
  "summary": "<2-3 sentences in Chinese summarizing the overall quality>",
  "key_issues": ["<issue 1 in Chinese>", "<issue 2 in Chinese>"],
  "strengths":  ["<strength 1 in Chinese>", "<strength 2 in Chinese>"]
}

Be strict but fair. A score of 9–10 means the scene is exemplary. 7–8 is good with minor issues. 5–6 has noticeable problems. Below 5 has significant flaws."""


# ---------------------------------------------------------------------------
# AI-2 系统 Prompt：10 场景汇总 + Prompt 更新建议
# ---------------------------------------------------------------------------

SUMMARIZER_SYSTEM_PROMPT = """You are a senior AI prompt engineer specializing in 3D urban scene generation. You have received evaluation records for the most recent 10 overlap-free (clean) scenes generated by an AI system.

Your task:
1. Identify recurring quality issues across these 10 scenes
2. Identify recurring strengths
3. Produce a concise improvement note that can be APPENDED to the generation system prompt to help the AI do better next time

The improvement note must:
- Be written in English (it will be inserted into an English system prompt)
- Be specific and actionable (not generic advice)
- Reference specific metrics that scored low
- Be 100-300 words
- Be wrapped exactly between these markers:
  === QUALITY IMPROVEMENT NOTES ===
  <your improvement text here>
  === END QUALITY IMPROVEMENT NOTES ===

Return ONLY valid JSON in this exact format:
{
  "common_issues": ["<issue 1>", "<issue 2>", "<issue 3>"],
  "common_strengths": ["<strength 1>", "<strength 2>"],
  "improvement_suggestions": "<brief summary of what needs improvement, in Chinese>",
  "prompt_addition": "=== QUALITY IMPROVEMENT NOTES ===\\n<improvement text>\\n=== END QUALITY IMPROVEMENT NOTES ==="
}

Be specific. Reference actual patterns you see in the scores and comments."""


# ---------------------------------------------------------------------------
# 内部工具函数
# ---------------------------------------------------------------------------

def _call_ai2(system_prompt: str, user_content: str) -> dict:
    """调用 AI-2 DeepSeek API，返回解析后的 JSON dict。"""
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {DEEPSEEK_API_KEY_2}",
    }
    payload = {
        "model": DEEPSEEK_MODEL,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": user_content},
        ],
        "temperature": DEEPSEEK_EVALUATOR_TEMP,
        "max_tokens": 2000,
        "response_format": {"type": "json_object"},
    }
    resp = requests.post(DEEPSEEK_API_URL, headers=headers, json=payload, timeout=120)
    resp.raise_for_status()
    return json.loads(resp.json()["choices"][0]["message"]["content"])


def _default_eval_result() -> dict:
    """AI-2 调用失败时的安全默认值。"""
    return {
        "overall_score": None,
        "metrics": {},
        "summary": "AI-2 评估调用失败，跳过本次评分。",
        "key_issues": [],
        "strengths": [],
    }


# ---------------------------------------------------------------------------
# 公开接口
# ---------------------------------------------------------------------------

def evaluate_scene(
    original_prompt: str,
    scene_data: dict,
    overlaps: list,
    attempt: int,
) -> dict:
    """
    调用 AI-2 对单次场景生成结果进行质量评分。

    参数:
        original_prompt — 用户原始文本提示词
        scene_data      — 本次生成的场景 dict（含 buildings / roads）
        overlaps        — check_overlaps() 返回的重叠列表（空列表 = 无重叠）
        attempt         — 当前是第几次尝试（1-based）

    返回:
        dict with keys: overall_score, metrics, summary, key_issues, strengths
        调用失败时返回 _default_eval_result()，不抛出异常。
    """
    # 构建发给 AI-2 的用户消息
    overlap_desc = (
        f"No overlaps detected (clean scene)."
        if not overlaps
        else (
            f"{len(overlaps)} overlap(s) detected:\n"
            + "\n".join(
                f"  - {o.get('a_desc', '?')} overlaps {o.get('b_desc', '?')}"
                f" (area: {o.get('overlap_area_m2', 0):.2f} m²)"
                for o in overlaps
            )
        )
    )

    scene_json_str = json.dumps(scene_data, ensure_ascii=False, indent=2)

    user_content = (
        f"=== ORIGINAL PROMPT ===\n{original_prompt}\n\n"
        f"=== ATTEMPT NUMBER ===\n{attempt}\n\n"
        f"=== GENERATED SCENE JSON ===\n{scene_json_str}\n\n"
        f"=== OVERLAP STATUS ===\n{overlap_desc}"
    )

    try:
        result = _call_ai2(EVALUATOR_SYSTEM_PROMPT, user_content)
        # 规范化 overall_score 到 1 位小数
        if "overall_score" in result and result["overall_score"] is not None:
            result["overall_score"] = round(float(result["overall_score"]), 1)
        return result
    except Exception as exc:
        print(f"[AI-2] WARNING: 评分调用失败 — {exc}")
        return _default_eval_result()


def summarize_and_update(
    clean_evals: list,
    skills_dir: Path,
) -> None:
    """
    调用 AI-2 汇总最近 N 个干净场景的评分，然后更新对应风格的 system_prompt.txt。

    参数:
        clean_evals — 最近 N 个干净场景的 eval_log 条目列表
        skills_dir  — skills/ 目录路径（Path 对象）
    """
    if not clean_evals:
        return

    # 构建发给 AI-2 的汇总消息
    records_str = json.dumps(clean_evals, ensure_ascii=False, indent=2)
    user_content = (
        f"Here are the evaluation records for the most recent {len(clean_evals)} "
        f"clean (overlap-free) scenes:\n\n{records_str}"
    )

    try:
        summary = _call_ai2(SUMMARIZER_SYSTEM_PROMPT, user_content)
    except Exception as exc:
        print(f"[AI-2] WARNING: 汇总调用失败 — {exc}")
        return

    prompt_addition = summary.get("prompt_addition", "")
    if not prompt_addition:
        print("[AI-2] WARNING: AI-2 未返回 prompt_addition，跳过更新。")
        return

    # 确定需要更新的风格集合（含 None → _common）
    styles_in_batch: set = {e.get("style") for e in clean_evals}

    # 更新每个涉及风格的 system_prompt.txt，以及 _common 兜底
    targets = list(styles_in_batch) + [None]   # None → _common

    for style in targets:
        if style:
            prompt_path = skills_dir / style / "assets" / "system_prompt.txt"
        else:
            prompt_path = skills_dir / "_common" / "assets" / "base_system_prompt.txt"

        if not prompt_path.exists():
            print(f"[AI-2] WARNING: 找不到 {prompt_path}，跳过。")
            continue

        original_text = prompt_path.read_text(encoding="utf-8")

        # 删除旧的 QUALITY IMPROVEMENT NOTES 块（如有）
        cleaned = re.sub(
            r"\n*=== QUALITY IMPROVEMENT NOTES ===.*?=== END QUALITY IMPROVEMENT NOTES ===\n*",
            "",
            original_text,
            flags=re.DOTALL,
        ).rstrip()

        # 追加新的 improvement notes
        updated = cleaned + "\n\n" + prompt_addition + "\n"
        prompt_path.write_text(updated, encoding="utf-8")
        label = style if style else "_common (base)"
        print(f"[AI-2] system_prompt 已更新: {prompt_path.name} [{label}]")
